version: "3.9"
x-logging:
  &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    stop_grace_period: 5m
    image: ghcr.io/paradigmxyz/reth
    volumes:
      - revm-el-data:/var/lib/revm
      - jwtsecret:/var/lib/jwtsecret
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - reth
      - node
      - --authrpc.jwtsecret
      - /var/lib/jwtsecret/jwtsecret
      - --datadir
      - /var/lib/revm
      - --chain
      - ${NETWORK}
      - --metrics
      - 0.0.0.0:3000
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.port
      - "8545"
      - --http.api
      - web3,trace,debug
      - --ws
      - --ws.addr
      - "0.0.0.0"
      - --ws.port
      - "8546"
  consensus:
    restart: "unless-stopped"
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
    stop_grace_period: 1m
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lighthouse/beacon/ee-secret
    ports:
      - "9000:9000"
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - lighthouse
      - beacon_node
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - "0.0.0.0"
      - --http-port
      - "5052"
      - --network
      - ${NETWORK}
      - --port
      - "9000"
      - --target-peers
      - "80"
      - --execution-endpoint
      - http://execution:8551
      - --execution-jwt
      - /var/lib/lighthouse/beacon/ee-secret/jwtsecret
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - "0.0.0.0"
      - --metrics-port
      - "8008"
      - --validator-monitor-auto
volumes:
  revm-el-data:
  lhconsensus-data:
  jwtsecret:
